
[general]  # General parameters that apply to the whole simulation.

jobname         = "FTPS-CPA+DMFT_U={u:.0f}"  # The job name of the simulation. Used for generating SLURM scripts.
mail            = "dylan.jones@uni-a.de"  # The email address for job notifications. Used for generating SLURM scripts.
location        = "."  # The directory where the simulation is run.
output          = "out.h5"  # The name of the output file.
tmpdir          = ".tmp/"  # The directory where temporary files are stored.
n_loops         = 3  # The total number of iterations to perfom.
restart         = true  # Flag if the calculation should resume from previous results or start over.

# Model parameters
lattice         = "bethe"  # The lattice type
gf_struct       = [["up", 1], ["dn", 1]]  # The structure of the Greens function
# half_bandwidth = 2.0  # The half bandwidth of the lattice DOS
t               = 1.0  # The hopping parameter (alternative to half_bandwidth)
conc            = [0.7, 0.3]  # The concentrations of the components. Can either be a single value (no CPA) or a list of numbers.
eps             = [0.0, +0.0]  # The on-site energies of the components.
h_field         = 0  # The magnetic Zeeman field of the components.
u               = 4  # The Hubbard interaction strength (Coulomb repulsion) of the components.
mu              = 0  # The chemiocal potential
# beta          = 10  # The inverse temperature

# REAL MESH (if beta is not given)
n_w             = 3001  # Number of mesh points
w_range         = [-8, 8]  # Frequency range
eta             = -1  # Complex broadening (Negative: eta = 6 / nbath)
# MATSUBARA MESH (if beta given)
# n_iw          = 1028  # Number of mesh points

# DMFT parameters
mixing_dmft     = 0.5  # Mixing of the DMFT self energy
tol_dmft        = 1e-2  # Tolerance for the DMFT self-consistency check

# CPA parameters
mixing_cpa      = 1.0  # Mixing of the CPA self energy
method_cpa      = "iter"  # Method used for computing the CPA self energy
maxiter_cpa     = 1000  # Number of iterations  for computing the CPA self energy
tol_cpa         = 1e-4  # Tolerance for the CPA self-consistency check
verbosity_cpa   = 1  # verbosity level of the CPA iterations


[solver]  # Solver specific parameters

type             = "ftps"  # Solver used to solve impurity problem

bath_fit         = true  # DiscretizeBath vs BathFitter
n_bath           = 20  # The number of bath sites used by the FTPS solver

# Tevo parameters
time_steps       = 100  # Number of time steps for the time evolution.
dt               = 0.1  # Time step for the time evolution.
method           = "TDVP_2"  # Time evolution method, "TDVP", "TDVP_2" or "TEBD"

# DMRG parameters
sweeps           = 10  # Number of DMRG sweeps (default 15)

# Used for Tevo and DMRG parameters
tw               = 1e-9  # Truncated weight for every link. (default 1e-9)
maxm             = 100  # Maximum bond dimension. (default 100)
nmax             = 40  # Maximal Number of Krylov vectors created. (default 40)
